# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2009

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Tech: /
  Personal: https://blog.deepumohan.com/
  മലയാളം: https://ithokkethanne.blogspot.com/
  About: https://deepumohan.com/
  # Tags: /tags
  # Categories: /categories

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: 'This <span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/StillImage" rel="dct:type">work</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://deepumohan.com/" property="cc:attributionName" rel="cc:attributionURL">Deepu Mohan Puthrote</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a> <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  stack-overflow: https://stackoverflow.com/users/598444/warfox
  twitter: https://twitter.com/deepumohanp
  facebook: https://fb.com/deepu.mohan.p
  linkedin: https://linkedin.com/in/deepumohanp
  google:
  github: https://github.com/WarFox
  weibo:
  zhihu:
  douban:
  pocket: https://getpocket.com/@deepumohanp
  tumblr: https://deepumohan.com/deepumohanp
  instagram: https://instagram.com/deepumohanp

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname: warfox

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.6.0
