version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  hugo: circleci/hugo@1.3.0

# jobs are orchestrated using workflows
jobs:
  html-proofer:
    docker:
      - image: cimg/ruby:3.2.1
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - restore_cache:
          keys:
            - gem-cache-5.0.6
            - gem-cache
      - run: gem install html-proofer -v 5.0.6
      - save_cache:
          key: gem-cache-5.0.6
          paths:
            - ~/.rubygems
      - run: mv /tmp/workspace/public /tmp/workspace/tech
      - run: |
          ~/.rubygems/bin/htmlproofer \
          --allow-hash-href \
          --disable-external \
          --ignore-empty-alt \
          --ignore-urls "/site.webmanifest,/safari-pinned-tab.svg,/apple-touch-icon.png,/favicon-16x16.png,/favicon-32x32.png,/favicon.ico,/index.xml" \
          /tmp/workspace/

  deploy:
    parameters:
      role-arn:
        type: string
      environment:
        type: string
    docker:
      - image: 'cibuilds/hugo:0.111.3'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace/
      - run: pwd
      - run: ls -lah
      - run: ls -lah /tmp/workspace/
      - run: ls -lah ~/project
      - aws-cli/setup:
          profile-name: setup
      - aws-cli/role-arn-setup:
          profile-name: default
          role-arn: <<parameters.role-arn>>
          source-profile: setup
      - run:
          name: hugo deploy
          command: |
            hugo 
            hugo deploy --config ~/project/config.toml --source /tmp/workspace/public --target <<parameters.environment>> --dryRun

# Build workflows using jobs and orbs
workflows:
  build_deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          source: .
          version: '0.111.3'

      - html-proofer:
          requires:
            - hugo/build

      - deploy: # deploy to staging from feature branches
          name: deploy-to-staging
          context: org-context
          role-arn: arn:aws:iam::106172881994:role/DeployStagingDeepumohanCom
          environment: staging
          requires:
            - html-proofer
          filters:
            branches:
              ignore: master

      - deploy: # deploy on master branch
          name: deploy-to-production
          context: org-context
          role-arn: arn:aws:iam::106172881994:role/DeployDeepumohanCom
          environment: production
          requires:
            - html-proofer
          filters:
            branches:
              only: master
