version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-s3: circleci/aws-s3@4.0.0
  hugo: circleci/hugo@1.3.0

# jobs are orchestrated using workflows
jobs:
  html-proofer:
    docker:
      - image: cimg/ruby:3.2.1
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - restore_cache:
          keys:
            - gem-cache-5.0.6
            - gem-cache
      - run: gem install html-proofer -v 5.0.6
      - save_cache:
          key: gem-cache-5.0.6
          paths:
            - ~/.rubygems
      - run: mv /tmp/workspace/public /tmp/workspace/tech
      - run: |
          ~/.rubygems/bin/htmlproofer \
          --allow-hash-href \
          --disable-external \
          --ignore-empty-alt \
          --ignore-urls "/site.webmanifest,/safari-pinned-tab.svg,/apple-touch-icon.png,/favicon-16x16.png,/favicon-32x32.png,/favicon.ico,/index.xml" \
          /tmp/workspace/

  deploy:
    parameters:
      role_arn:
        type: string
      s3_location:
        type: string
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - run: ls -lah /tmp/workspace/
      - aws-cli/setup:
          profile_name: default
      - aws-cli/role_arn_setup:
          profile_name: deploy
          role_arn: <<parameters.role_arn>>
          source_profile: default
      - aws-s3/copy:
          arguments: --recursive
          from: /tmp/workspace/public/
          to: <<parameters.s3_location>>
          profile_name: deploy # need to explicitly provide profile_name

# Build workflows using jobs and orbs
workflows:
  build_deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          source: .
          version: '0.118.2'

      - html-proofer:
          requires:
            - hugo/build

      - deploy: # deploy to staging
          name: deploy-staging
          context: org-context
          role_arn: arn:aws:iam::106172881994:role/DeployStagingDeepumohanCom
          s3_location: 's3://staging.deepumohan.com/tech/'
          requires:
            - html-proofer

      - deploy: # deploy on main branch
          name: deploy-production
          context: org-context
          role_arn: arn:aws:iam::106172881994:role/DeployDeepumohanCom
          s3_location: 's3://deepumohan.com/tech/'
          requires:
            - deploy-staging
          filters:
            branches:
              only: main
